name: lint
on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - uses: actions/checkout@v3

      - name: golangci-lint
        run: make lint
  
  docker:
    name: docker buildable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: buildable
        run: docker build -t buildable .
